{
 "title": "Hbase",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15m",
 "panels": [
  { "title": "RegionServer: Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Regions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select total_regions_across_regionservers where entityName=hbase"
    }
   ]
  },
  {
   "title": "Region In Transition",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "select regions_in_transition" }
   ]
  },
  {
   "title": "Total BlockCache Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select total_block_cache_blocks_cached_across_regionservers where entityName=hbase"
    }
   ]
  },
  {
   "title": "Total Resident Memory",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select total_mem_rss_across_regionservers where entityName=hbase"
    }
   ]
  },
  {
   "title": "Total Store File Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select total_storefiles_size_across_regionservers where entityName=hbase"
    }
   ]
  },
  {
   "title": "Total Store Files",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select total_storefiles_across_regionservers where entityName=hbase"
    }
   ]
  },
  {
   "title": "Total Memstore Size",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "select total_memstore_size_across_regionservers as \" \" where entityName=hbase"
    }
   ]
  },
  {
   "title": "Parallel GC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 5 },
   "targets": [
    {
     "target": "select integral(gc_count_par_new_rate_across_regionservers) where entityName=hbase"
    }
   ]
  },
  {
   "title": "Parallel GC time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 5 },
   "targets": [
    {
     "target": "select integral(gc_time_ms_par_new_rate_across_regionservers) where entityName=hbase"
    }
   ]
  },
  {
   "title": "Webserver Responsiveness",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 5 },
   "targets": [
    {
     "target": "select web_metrics_collection_duration_across_regionservers where entityName=hbase"
    }
   ]
  },
  { "title": "RegionServer: BlockCache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Hit Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select block_cache_hit_rate_across_regionservers where entityName=hbase"
    }
   ]
  },
  {
   "title": "Miss Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select block_cache_miss_rate_across_regionservers where entityName=hbase"
    }
   ]
  },
  {
   "title": "Free Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select total_block_cache_free_size_across_regionservers where entityName=hbase"
    }
   ]
  },
  {
   "title": "Total Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select total_block_cache_size_across_regionservers where entityName=hbase"
    }
   ]
  },
  {
   "title": "Eviction Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select block_cache_evicted_rate_across_regionservers where entityName=hbase"
    }
   ]
  },
  {
   "title": "Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "target": "select block_cache_hit_ratio_across_regionservers where entityName=hbase"
    }
   ]
  },
  {
   "title": "Total Size Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "select total_block_cache_size_across_regionservers where entityName=hbase"
    }
   ]
  },
  { "title": "RegionServer:Maintenance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Compaction Queue Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select compaction_queue_size_across_regionservers where entityName=hbase"
    }
   ]
  },
  {
   "title": "Flush Queue Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select flush_queue_size_across_regionservers where entityName=hbase"
    }
   ]
  },
  {
   "title": "Unexpected PS Exit",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select total_unexpected_exits_rate_across_regionservers where entityName=hbase"
    }
   ]
  },
  {
   "title": "OOM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select oom_exits_rate_across_regionservers where entityName=hbase"
    }
   ]
  },
  {
   "title": "Swap Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select mem_swap_across_regionservers where entityName=hbase"
    }
   ]
  },
  {
   "title": "Slow get rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select total_slow_get_rate_across_regionservers where entityName=hbase"
    }
   ]
  },
  {
   "title": "Slow Put rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select total_slow_put_rate_across_regionservers where entityName=hbase"
    }
   ]
  },
  {
   "title": "Log Error",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select log_error_rate_across_regionservers where entityName=hbase"
    }
   ]
  },
  {
   "title": "Total Static Index Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "select total_static_index_size_across_regionservers where entityName=hbase"
    }
   ]
  },
  {
   "title": "Total Store File Index Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "select total_storefile_index_size_across_regionservers where entityName=hbase"
    }
   ]
  },
  {
   "title": "Total Mutations without WAL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "select total_mutations_without_wal_rate_across_regionservers where entityName=hbase"
    }
   ]
  },
  {
   "title": "Total GC Pause Time 99.9P",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "select total_pause_time_with_gc_99_9th_percentile_across_regionservers where entityName=hbase"
    }
   ]
  }
 ]
}