{
 "title": "HDFS",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30m",
 "panels": [
  { "title": "Health and Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Health",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select  health_concerning_rate * 100 as \"concerning health\", health_bad_rate * 100 as \"bad health\", health_disabled_rate * 100 as \"disabled health\", health_unknown_rate * 100 as \"unknown health\" where entityName=hdfs"
    }
   ]
  },
  {
   "title": "Alerts Across DataNodes",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "select integral(alerts_rate_across_datanodes) where entityName=hdfs"
    }
   ]
  },
  {
   "title": "HDFS Capacity",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "select dfs_capacity, dfs_capacity_used, dfs_capacity_used_non_hdfs where entityName=hdfs"
    }
   ]
  },
  {
   "title": "Average Disk Flush Time Across DataNodes",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "target": "select flush_nanos_avg_time_across_datanodes where entityName=hdfs"
    }
   ]
  },
  {
   "title": "Send Data Packet Blocked on Network Average Time Across DataNodes",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "target": "select send_data_packet_blocked_on_network_nanos_avg_time_across_datanodes where entityName=hdfs"
    }
   ]
  },
  {
   "title": "Send Data Packet Transfer Average Time Across DataNodes",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "target": "select send_data_packet_transfer_nanos_avg_time_across_datanodes where entityName=hdfs"
    }
   ]
  },
  {
   "title": "Total Transceivers Across DataNodes",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "select total_xceivers_across_datanodes where entityName=hdfs"
    }
   ]
  },
  {
   "title": "Total Blocks Read Across DataNodes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "b/s" } },
   "targets": [
    {
     "target": "select total_blocks_read_rate_across_datanodes where entityName=hdfs"
    }
   ]
  },
  {
   "title": "Total Bytes Read Across DataNodes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "target": "select total_bytes_read_rate_across_datanodes where entityName=hdfs"
    }
   ]
  },
  {
   "title": "Total Bytes Written Across DataNodes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "target": "select total_bytes_written_rate_across_datanodes where entityName=hdfs"
    }
   ]
  },
  { "title": "Data Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU System",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select cpu_system_rate_across_datanodes where entityName=hdfs"
    }
   ]
  },
  {
   "title": "CPU User",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select cpu_user_rate_across_datanodes where entityName=hdfs"
    }
   ]
  },
  {
   "title": "JVM Heap Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select jvm_heap_used_mb_across_datanodes where entityName=hdfs"
    }
   ]
  },
  {
   "title": "JVM GC Operations",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 16 },
   "targets": [
    {
     "target": "select jvm_gc_rate_across_datanodes where entityName=hdfs"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select mem_rss_across_datanodes where entityName=hdfs"
    }
   ]
  },
  {
   "title": "Unexpected PS Exits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select unexpected_exits_rate_across_datanodes where entityName=hdfs"
    }
   ]
  },
  {
   "title": "Web Server Responsiveness",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "select web_metrics_collection_duration_across_datanodes where entityName=hdfs"
    }
   ]
  },
  {
   "title": "Open RPC Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select rpc_num_open_connections_across_datanodes where entityName=hdfs"
    }
   ]
  },
  {
   "title": "Average RPC Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "select rpc_queue_time_avg_time_across_datanodes where entityName=hdfs"
    }
   ]
  },
  {
   "title": "Average RPC Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "select rpc_processing_time_avg_time_across_datanodes where entityName=hdfs"
    }
   ]
  },
  {
   "title": "RPC Authorisation Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select rpc_authorization_failures_rate_across_datanodes where entityName=hdfs"
    }
   ]
  },
  {
   "title": "RPC Authentication Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select rpc_authentication_failures_rate_across_datanodes where entityName=hdfs"
    }
   ]
  },
  {
   "title": "RPC Received Bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "target": "select rpc_received_bytes_rate_across_datanodes where entityName=hdfs"
    }
   ]
  },
  {
   "title": "RPC Sent Bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "target": "select rpc_sent_bytes_rate_across_datanodes where entityName=hdfs"
    }
   ]
  },
  {
   "title": "HDFS Blocks Uncached",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Blocks/sec" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select blocks_uncached_rate_across_datanodes where entityName=hdfs"
    }
   ]
  },
  {
   "title": "HDFS Blocks Cached",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Blocks/sec" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select blocks_cached_rate_across_datanodes where entityName=hdfs"
    }
   ]
  },
  { "title": "HDFS Blocks and Files", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Files Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select files_total where entityName=hdfs"
    }
   ]
  },
  {
   "title": "Blocks Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select blocks_total where entityName=hdfs"
    }
   ]
  },
  {
   "title": "Excess Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select excess_blocks where entityName=hdfs"
    }
   ]
  },
  {
   "title": "Missing Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select missing_blocks where entityName=hdfs"
    }
   ]
  },
  {
   "title": "Blocks with Corrupt Replicas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select blocks_with_corrupt_replicas where entityName=hdfs"
    }
   ]
  },
  {
   "title": "Pending Deletion Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select pending_deletion_blocks where entityName=hdfs"
    }
   ]
  },
  {
   "title": "Scheduled Replication Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select scheduled_replication_blocks where entityName=hdfs"
    }
   ]
  },
  {
   "title": "Pending Replication Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select pending_replication_blocks where entityName=hdfs"
    }
   ]
  },
  {
   "title": "Block Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "select block_capacity where entityName=hdfs"
    }
   ]
  },
  {
   "title": "Under-replicated Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select under_replicated_blocks where entityName=hdfs"
    }
   ]
  }
 ]
}