{
 "title": "Amazon S3",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   {
    "name": "region",
    "query": {}
   },
   { "name": "bucket", "label": "BucketName" }
  ]
 },
 "panels": [
  { "title": "Storage Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "No Of Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "BucketName": "$bucket" },
     "metricName": "NumberOfObjects",
     "namespace": "AWS/S3",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Bucket Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dimensions": { "BucketName": "$bucket" },
     "metricName": "BucketSizeBytes",
     "namespace": "AWS/S3",
     "period": "300",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  { "title": "Request Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Get Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricName": "GetRequests",
     "namespace": "AWS/S3",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "Put Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricName": "PutRequests",
     "namespace": "AWS/S3",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "Post Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricName": "PostRequests",
     "namespace": "AWS/S3",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "List Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricName": "ListRequests",
     "namespace": "AWS/S3",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "Head Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricName": "HeadRequests",
     "namespace": "AWS/S3",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "All Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "metricName": "AllRequests",
     "namespace": "AWS/S3",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "Bytes Downloaded",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricName": "BytesDownloaded",
     "namespace": "AWS/S3",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Bytes Uploaded",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricName": "BytesUploaded",
     "namespace": "AWS/S3",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "First Byte Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricName": "FirstByteLatency",
     "namespace": "AWS/S3",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Total Reqs Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricName": "TotalRequestLatency",
     "namespace": "AWS/S3",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "4xx Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricName": "4xxErrors",
     "namespace": "AWS/S3",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "5xx Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricName": "5xxErrors",
     "namespace": "AWS/S3",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "SampleCount"
    }
   ]
  }
 ]
}