{
 "title": "Zookeeper",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30m",
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Health",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select  health_concerning_rate * 100 as \"concerning health\", health_bad_rate * 100 as \"bad health\", health_disabled_rate * 100 as \"disabled health\", health_unknown_rate * 100 as \"unknown health\" where entityName RLIKE \"zookeeper-[a-z 0-9]*\""
    }
   ]
  },
  {
   "title": "Critical Events and Alerts",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select integral(alerts_rate), integral(events_critical_rate) where category=role and serviceName RLIKE \"zookeeper-[a-z 0-9]*\""
    }
   ]
  },
  {
   "title": "Canary Duration",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select canary_duration where entityName RLIKE \"zookeeper-[a-z 0-9]*\""
    }
   ]
  },
  {
   "title": "CPU Cores Used",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select cpu_user_rate where category=ROLE and serviceName RLIKE \"zookeeper-[a-z 0-9]*\""
    },
    {
     "target": "select cpu_system_rate  where category=ROLE and serviceName RLIKE \"zookeeper-[a-z 0-9]*\""
    }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Total Open Connections Across Servers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select total_open_connections_across_servers where entityName RLIKE \"zookeeper-[a-z 0-9]*\""
    }
   ]
  },
  {
   "title": "Total Outstanding Requests Across Servers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select total_outstanding_requests_across_servers WHERE entityName RLIKE \"zookeeper-[a-z 0-9]*\""
    }
   ]
  },
  {
   "title": "Fsync Threshold Exceed Count Across Servers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select fsync_threshold_exceed_rate_across_servers where entityName RLIKE \"zookeeper-[a-z 0-9]*\""
    }
   ]
  },
  {
   "title": "Total Data Nodes Across Servers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select total_data_nodes_across_servers where entityName RLIKE \"zookeeper-[a-z 0-9]*\""
    }
   ]
  },
  {
   "title": "Total Data Size Across Servers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select total_data_size_across_servers where entityName RLIKE \"zookeeper-[a-z 0-9]*\""
    }
   ]
  },
  {
   "title": "Total Packets Transmitted Across Servers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select total_packets_transmit_rate_across_servers where entityName RLIKE \"zookeeper-[a-z 0-9]*\""
    }
   ]
  },
  {
   "title": "Total Packets Received Across Servers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select total_packets_receive_rate_across_servers where entityName RLIKE \"zookeeper-[a-z 0-9]*\""
    }
   ]
  },
  {
   "title": "Avg Client Response Size Across Servers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select last_client_response_size_across_servers where entityName RLIKE \"zookeeper-[a-z 0-9]*\""
    }
   ]
  },
  {
   "title": "Maximum Client Response Size Across Servers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select max_client_response_size_across_servers where entityName RLIKE \"zookeeper-[a-z 0-9]*\""
    }
   ]
  },
  {
   "title": "Average Request Latency Across Servers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select average_request_latency_across_servers where entityName RLIKE \"zookeeper-[a-z 0-9]*\""
    }
   ]
  },
  {
   "title": "Maximum Request Latency Across Servers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select max_request_latency_across_servers where entityName RLIKE \"zookeeper-[a-z 0-9]*\""
    }
   ]
  }
 ]
}